[package]
name = "juggernaut"
version = "0.1.0"
authors = ["Shashanka N <shasn@cisco.com>"]
edition = "2018"

[dependencies]
web-view = { git = "https://github.com/Boscop/web-view" }
serde_json = "1.0.39"
serde = "1.0"
serde_derive = "1.0"
walkdir = "2"
glob = "0.3.0"